// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQjCFH74PkSoKPP5lib9OTtT5XXKFN9vw',
    appId: '1:583448225200:web:76c3ac32ac6c5d9846e275',
    messagingSenderId: '583448225200',
    projectId: 'afric-shop-yonas',
    authDomain: 'afric-shop-yonas.firebaseapp.com',
    storageBucket: 'afric-shop-yonas.appspot.com',
    measurementId: 'G-HWP4NY55WK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8i1JCKBhGIyR5N3dDjYwFFF1W6govvxg',
    appId: '1:583448225200:android:f7ffcb75ba864f9b46e275',
    messagingSenderId: '583448225200',
    projectId: 'afric-shop-yonas',
    storageBucket: 'afric-shop-yonas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO_rXX5KPzk54leNAYRn3cAYiDLjvkqnk',
    appId: '1:583448225200:ios:d8546558df6453c346e275',
    messagingSenderId: '583448225200',
    projectId: 'afric-shop-yonas',
    storageBucket: 'afric-shop-yonas.appspot.com',
    iosClientId: '583448225200-grqvj3e0vq4o6jrhr9e0fp5iahuctd1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.africShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO_rXX5KPzk54leNAYRn3cAYiDLjvkqnk',
    appId: '1:583448225200:ios:d8546558df6453c346e275',
    messagingSenderId: '583448225200',
    projectId: 'afric-shop-yonas',
    storageBucket: 'afric-shop-yonas.appspot.com',
    iosClientId: '583448225200-grqvj3e0vq4o6jrhr9e0fp5iahuctd1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.africShopApp',
  );
}
